name: Upload Airflow DAGs to S3

on:
  push:
    branches:
      - master

jobs:

  deploy-dags:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload DAGs to S3
        run: |
          aws s3 sync dags s3://real-estate-dsr-2/dags/ --delete

      - name: Zip Plugins Folder
        run: |
          zip -r plugins.zip plugins

      - name: Upload Plugins Zip to S3
        run: |
          aws s3 cp plugins.zip s3://real-estate-dsr-2/plugins.zip
      - name: Upload requirements
        run: |
          aws s3 sync requirements.txt s3://real-estate-dsr-2/requirements.txt